# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'aftertouches/about.ui'
#
# Created: Sat Apr 19 19:38:02 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(500, 315)
        Dialog.setMinimumSize(QtCore.QSize(500, 315))
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setHorizontalSpacing(12)
        self.gridLayout.setVerticalSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 9, 0, 1, 2)
        self.title = QtGui.QLabel(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title.sizePolicy().hasHeightForWidth())
        self.title.setSizePolicy(sizePolicy)
        self.title.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.title.setWordWrap(True)
        self.title.setObjectName("title")
        self.gridLayout.addWidget(self.title, 0, 1, 2, 1)
        self.version = QtGui.QLabel(Dialog)
        self.version.setObjectName("version")
        self.gridLayout.addWidget(self.version, 4, 1, 1, 1)
        self.label = QtGui.QLabel(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/common/resources/icon.svg"))
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 9, 1)
        self.copyright = QtGui.QLabel(Dialog)
        self.copyright.setWordWrap(True)
        self.copyright.setObjectName("copyright")
        self.gridLayout.addWidget(self.copyright, 3, 1, 1, 1)
        self.contributorsTitle = QtGui.QLabel(Dialog)
        self.contributorsTitle.setObjectName("contributorsTitle")
        self.gridLayout.addWidget(self.contributorsTitle, 6, 1, 1, 1)
        self.licence = QtGui.QLabel(Dialog)
        self.licence.setObjectName("licence")
        self.gridLayout.addWidget(self.licence, 5, 1, 1, 1)
        self.intro = QtGui.QLabel(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.intro.sizePolicy().hasHeightForWidth())
        self.intro.setSizePolicy(sizePolicy)
        self.intro.setWordWrap(True)
        self.intro.setObjectName("intro")
        self.gridLayout.addWidget(self.intro, 2, 1, 1, 1)
        self.scrollArea = QtGui.QScrollArea(Dialog)
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 342, 57))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.contributors = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contributors.sizePolicy().hasHeightForWidth())
        self.contributors.setSizePolicy(sizePolicy)
        self.contributors.setStyleSheet("")
        self.contributors.setTextFormat(QtCore.Qt.RichText)
        self.contributors.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.contributors.setWordWrap(True)
        self.contributors.setObjectName("contributors")
        self.verticalLayout.addWidget(self.contributors)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 7, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "About ...", None, QtGui.QApplication.UnicodeUTF8))
        self.title.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; font-style:italic;\">After Touches</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.version.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Version</span>: 0.1</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.copyright.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p>Copyright 2014 Andrew Robinson (<a href=\"mailto:andrewjrobinson+sr@gmail.com\"><span style=\" text-decoration: underline; color:#0000ff;\">andrewjrobinson@gmail.com</span></a>)</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.contributorsTitle.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Contributors</span>:</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.licence.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Licence</span>: LGPL 2+</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.intro.setText(QtGui.QApplication.translate("Dialog", "After Touches is a video analysis tool aimed coaches and sports people of all skill levels. After Touches is part of the SportsReview software suite.", None, QtGui.QApplication.UnicodeUTF8))
        self.contributors.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><ul type=\"square\" style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 0;\"><li style=\" margin-top:0px; margin-bottom:0px; margin-left:10px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Andrew Robinson (<a href=\"mailto:andrewjrobinson+sr@gmail.com\"><span style=\" text-decoration: underline; color:#0000ff;\">andrewjrobinson@gmail.com</span></a>)</li></ul></body></html>", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
