# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'aftertouches/aftertouches.ui'
#
# Created: Sat Apr 19 19:39:40 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(481, 444)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/common/resources/icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frameLabel = QtGui.QLabel(self.widget)
        self.frameLabel.setStyleSheet("border: 1px solid rgb(0, 85, 255);")
        self.frameLabel.setText("")
        self.frameLabel.setPixmap(QtGui.QPixmap(":/common/resources/icon.svg"))
        self.frameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.frameLabel.setObjectName("frameLabel")
        self.verticalLayout.addWidget(self.frameLabel)
        self.verticalLayout_2.addWidget(self.widget)
        self.frameSelectionFrame = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameSelectionFrame.sizePolicy().hasHeightForWidth())
        self.frameSelectionFrame.setSizePolicy(sizePolicy)
        self.frameSelectionFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameSelectionFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.frameSelectionFrame.setObjectName("frameSelectionFrame")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frameSelectionFrame)
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widgetControlWidget = QtGui.QWidget(self.frameSelectionFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetControlWidget.sizePolicy().hasHeightForWidth())
        self.widgetControlWidget.setSizePolicy(sizePolicy)
        self.widgetControlWidget.setObjectName("widgetControlWidget")
        self.gridLayout = QtGui.QGridLayout(self.widgetControlWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.prevFrameButton = QtGui.QPushButton(self.widgetControlWidget)
        self.prevFrameButton.setObjectName("prevFrameButton")
        self.gridLayout.addWidget(self.prevFrameButton, 0, 1, 1, 1)
        self.nextFrameButton = QtGui.QPushButton(self.widgetControlWidget)
        self.nextFrameButton.setObjectName("nextFrameButton")
        self.gridLayout.addWidget(self.nextFrameButton, 0, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 3, 1, 1)
        self.verticalLayout_3.addWidget(self.widgetControlWidget)
        self.previewLabel = QtGui.QLabel(self.frameSelectionFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.previewLabel.sizePolicy().hasHeightForWidth())
        self.previewLabel.setSizePolicy(sizePolicy)
        self.previewLabel.setMinimumSize(QtCore.QSize(0, 80))
        self.previewLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.previewLabel.setObjectName("previewLabel")
        self.verticalLayout_3.addWidget(self.previewLabel)
        self.frameSlider = QtGui.QSlider(self.frameSelectionFrame)
        self.frameSlider.setOrientation(QtCore.Qt.Horizontal)
        self.frameSlider.setObjectName("frameSlider")
        self.verticalLayout_3.addWidget(self.frameSlider)
        self.verticalLayout_2.addWidget(self.frameSelectionFrame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 481, 27))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionAbout_SportsReview = QtGui.QAction(MainWindow)
        self.actionAbout_SportsReview.setObjectName("actionAbout_SportsReview")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "After Touches - SportsReview", None, QtGui.QApplication.UnicodeUTF8))
        self.prevFrameButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Select previous frame", None, QtGui.QApplication.UnicodeUTF8))
        self.prevFrameButton.setText(QtGui.QApplication.translate("MainWindow", "< &Prev", None, QtGui.QApplication.UnicodeUTF8))
        self.prevFrameButton.setShortcut(QtGui.QApplication.translate("MainWindow", "Alt+P", None, QtGui.QApplication.UnicodeUTF8))
        self.nextFrameButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Select next frame", None, QtGui.QApplication.UnicodeUTF8))
        self.nextFrameButton.setText(QtGui.QApplication.translate("MainWindow", "&Next >", None, QtGui.QApplication.UnicodeUTF8))
        self.nextFrameButton.setShortcut(QtGui.QApplication.translate("MainWindow", "Alt+N", None, QtGui.QApplication.UnicodeUTF8))
        self.previewLabel.setText(QtGui.QApplication.translate("MainWindow", "No file open", None, QtGui.QApplication.UnicodeUTF8))
        self.frameSlider.setToolTip(QtGui.QApplication.translate("MainWindow", "Select Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "E&xit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_SportsReview.setText(QtGui.QApplication.translate("MainWindow", "About SportsReview", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
