# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'aftertouches/aftertouches.ui'
#
# Created: Thu Apr 24 12:58:51 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(586, 503)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/common/resources/icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frameLabel = QtGui.QLabel(self.widget)
        self.frameLabel.setStyleSheet("border: 1px solid rgb(0, 85, 255);")
        self.frameLabel.setText("")
        self.frameLabel.setPixmap(QtGui.QPixmap(":/common/resources/icon.svg"))
        self.frameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.frameLabel.setObjectName("frameLabel")
        self.verticalLayout.addWidget(self.frameLabel)
        self.verticalLayout_2.addWidget(self.widget)
        self.frameSelectionFrame = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameSelectionFrame.sizePolicy().hasHeightForWidth())
        self.frameSelectionFrame.setSizePolicy(sizePolicy)
        self.frameSelectionFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameSelectionFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.frameSelectionFrame.setObjectName("frameSelectionFrame")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frameSelectionFrame)
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2.addWidget(self.frameSelectionFrame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 586, 27))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.playbackToolBar = QtGui.QToolBar(MainWindow)
        self.playbackToolBar.setObjectName("playbackToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.playbackToolBar)
        MainWindow.insertToolBarBreak(self.playbackToolBar)
        self.timelineDockWidget = QtGui.QDockWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timelineDockWidget.sizePolicy().hasHeightForWidth())
        self.timelineDockWidget.setSizePolicy(sizePolicy)
        self.timelineDockWidget.setAllowedAreas(QtCore.Qt.BottomDockWidgetArea|QtCore.Qt.TopDockWidgetArea)
        self.timelineDockWidget.setObjectName("timelineDockWidget")
        self.dockWidgetContents = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidgetContents.sizePolicy().hasHeightForWidth())
        self.dockWidgetContents.setSizePolicy(sizePolicy)
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_4.setSpacing(2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frameSlider = QtGui.QSlider(self.dockWidgetContents)
        self.frameSlider.setMaximum(0)
        self.frameSlider.setOrientation(QtCore.Qt.Horizontal)
        self.frameSlider.setObjectName("frameSlider")
        self.verticalLayout_4.addWidget(self.frameSlider)
        self.previewLabel = QtGui.QLabel(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.previewLabel.sizePolicy().hasHeightForWidth())
        self.previewLabel.setSizePolicy(sizePolicy)
        self.previewLabel.setMinimumSize(QtCore.QSize(0, 80))
        self.previewLabel.setScaledContents(True)
        self.previewLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.previewLabel.setObjectName("previewLabel")
        self.verticalLayout_4.addWidget(self.previewLabel)
        self.timelineDockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.timelineDockWidget)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionPlay = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/common/resources/play.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPlay.setIcon(icon1)
        self.actionPlay.setObjectName("actionPlay")
        self.actionPlay2x = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/common/resources/play2x.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPlay2x.setIcon(icon2)
        self.actionPlay2x.setObjectName("actionPlay2x")
        self.actionPlay0_5x = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/common/resources/play0.5x.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPlay0_5x.setIcon(icon3)
        self.actionPlay0_5x.setObjectName("actionPlay0_5x")
        self.actionStart = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/common/resources/start.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStart.setIcon(icon4)
        self.actionStart.setObjectName("actionStart")
        self.actionEnd = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/common/resources/end.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEnd.setIcon(icon5)
        self.actionEnd.setObjectName("actionEnd")
        self.actionNext = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/common/resources/next.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNext.setIcon(icon6)
        self.actionNext.setObjectName("actionNext")
        self.actionPrev = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/common/resources/prev.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPrev.setIcon(icon7)
        self.actionPrev.setObjectName("actionPrev")
        self.actionPlayRev = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/common/resources/playrev.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPlayRev.setIcon(icon8)
        self.actionPlayRev.setObjectName("actionPlayRev")
        self.actionPlayRev2x = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/common/resources/playrev2x.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPlayRev2x.setIcon(icon9)
        self.actionPlayRev2x.setObjectName("actionPlayRev2x")
        self.actionPlayRev0_5x = QtGui.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/common/resources/playrev0.5x.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPlayRev0_5x.setIcon(icon10)
        self.actionPlayRev0_5x.setObjectName("actionPlayRev0_5x")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.playbackToolBar.addAction(self.actionStart)
        self.playbackToolBar.addSeparator()
        self.playbackToolBar.addAction(self.actionPlayRev0_5x)
        self.playbackToolBar.addAction(self.actionPlayRev2x)
        self.playbackToolBar.addAction(self.actionPlayRev)
        self.playbackToolBar.addSeparator()
        self.playbackToolBar.addAction(self.actionPlay)
        self.playbackToolBar.addAction(self.actionPlay2x)
        self.playbackToolBar.addAction(self.actionPlay0_5x)
        self.playbackToolBar.addSeparator()
        self.playbackToolBar.addAction(self.actionEnd)
        self.playbackToolBar.addSeparator()
        self.playbackToolBar.addAction(self.actionPrev)
        self.playbackToolBar.addAction(self.actionNext)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "After Touches - SportsReview", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.playbackToolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Playback", None, QtGui.QApplication.UnicodeUTF8))
        self.timelineDockWidget.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Timeline", None, QtGui.QApplication.UnicodeUTF8))
        self.frameSlider.setToolTip(QtGui.QApplication.translate("MainWindow", "Select Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.previewLabel.setText(QtGui.QApplication.translate("MainWindow", "No file open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "E&xit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setShortcut(QtGui.QApplication.translate("MainWindow", "Alt+F4", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlay.setText(QtGui.QApplication.translate("MainWindow", "Play", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlay.setToolTip(QtGui.QApplication.translate("MainWindow", "Play (normal speed)", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlay2x.setText(QtGui.QApplication.translate("MainWindow", "Play2x", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlay2x.setToolTip(QtGui.QApplication.translate("MainWindow", "Play (double speed)", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlay0_5x.setText(QtGui.QApplication.translate("MainWindow", "Play0.5x", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlay0_5x.setToolTip(QtGui.QApplication.translate("MainWindow", "Play (half speed)", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStart.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStart.setToolTip(QtGui.QApplication.translate("MainWindow", "Move to first frame", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEnd.setText(QtGui.QApplication.translate("MainWindow", "End", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEnd.setToolTip(QtGui.QApplication.translate("MainWindow", "Move to last frame", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNext.setText(QtGui.QApplication.translate("MainWindow", "Next", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNext.setToolTip(QtGui.QApplication.translate("MainWindow", "Next frame", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrev.setText(QtGui.QApplication.translate("MainWindow", "Prev", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrev.setToolTip(QtGui.QApplication.translate("MainWindow", "Previous frame", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlayRev.setText(QtGui.QApplication.translate("MainWindow", "PlayRev", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlayRev.setToolTip(QtGui.QApplication.translate("MainWindow", "Play reverse (normal speed)", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlayRev2x.setText(QtGui.QApplication.translate("MainWindow", "PlayRev2x", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlayRev2x.setToolTip(QtGui.QApplication.translate("MainWindow", "Play reverse (double speed)", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlayRev0_5x.setText(QtGui.QApplication.translate("MainWindow", "PlayRev0.5x", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlayRev0_5x.setToolTip(QtGui.QApplication.translate("MainWindow", "Play reverse (half speed)", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
